version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: mongo:latest
    steps:
      - checkout
      - run: 'npm install'
  test:
    docker:
      - image: circleci/node:lts
      - image: mongo:latest
    steps:
      - checkout
      - run: 'node node_modules/jasmine-node/bin/jasmine-node --captureExceptions test/server'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
