version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run: 'npm install'
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run: 'grunt test'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
